version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
      - MONGODB_CONNECTION_STRING_TEST=${MONGODB_CONNECTION_STRING_TEST}
      - NODE_ENV=development
    volumes:
      - ./mount/src:/app/src
